enum {
    MAX_CANVAS_WIDTH_EXCEEDED = -1,
    MAX_CANVAS_HEIGHT_EXCEEDED = -2,

    INCONSISTENT_CANVAS_WIDTH = -11,
    INCONSISTENT_CANVAS_HEIGHT = -12,

    ILLEGAL_BORDER_ELEMENT = -21,

    CANVAS_FILE_READ_REALLOC_FAILURE = -31,
};